/* ======================= الوحدات ======================= */
const UNITS = [
  {key:'u5', label:'الوحدة الخامسة: النباتات 🌱'},
  {key:'u6', label:'الوحدة السادسة: وطني الأردن 🏛️'},
  {key:'u7', label:'الوحدة السابعة: أصدقاء الأرض 🌍'},
  {key:'u8', label:'الوحدة الثامنة: شكرًا روضتي 🎓'},
  {key:'math', label:'عالم الرياضيات 🔢'},
];

/* ======================= بيانات الألعاب ======================= */
const LEVELS = [
  /* ---------- الوحدة الخامسة: النباتات ---------- */
  {id:'u5-letters', unit:'u5', title:'حروف: ل، ز، ج', icon:'🔤', chip:'#e3f7d9',
    questions:[
      {type:'mcq', prompt:'أيّ كلمة تبدأ بحرف (ل)؟', options:[{emoji:'🍋',text:'ليمون',correct:true},{emoji:'🐱',text:'قطة',correct:false}]},
      {type:'tf', prompt:'كلمة "لبن" تبدأ بحرف (ل).', correct:true},
      {type:'mcq', prompt:'أيّ صورة تبدأ بحرف (ز)؟', options:[{emoji:'🦒',text:'زرافة',correct:true},{emoji:'⚽',text:'كرة',correct:false}]},
      {type:'tf', prompt:'كلمة "منزل" تحتوي على حرف (ز).', correct:true},
      {type:'mcq', prompt:'أيّ صورة تبدأ بحرف (ج)؟', options:[{emoji:'🐫',text:'جمل',correct:true},{emoji:'🐭',text:'فأر',correct:false}]},
      {type:'tf', prompt:'كلمة "جزر" تبدأ بحرف (ج).', correct:true},
    ]},
  {id:'u5-english', unit:'u5', title:'English Letters: G, K', icon:'🔤', chip:'#f5e1ff',
    questions:[
      {type:'mcq', prompt:'Which word starts with letter G?', options:[{emoji:'🎁',text:'gift',correct:true},{emoji:'🐱',text:'cat',correct:false}]},
      {type:'tf', prompt:'The word "goat" starts with letter G.', correct:true},
      {type:'mcq', prompt:'Which word starts with letter G?', options:[{emoji:'👧',text:'girl',correct:true},{emoji:'🐶',text:'dog',correct:false}]},
      {type:'mcq', prompt:'Which word starts with letter K?', options:[{emoji:'🔑',text:'key',correct:true},{emoji:'☀️',text:'sun',correct:false}]},
      {type:'tf', prompt:'The word "kite" starts with letter K.', correct:true},
      {type:'mcq', prompt:'Which word starts with letter K?', options:[{emoji:'🦘',text:'kangaroo',correct:true},{emoji:'🐟',text:'fish',correct:false}]},
    ]},
  {id:'u5-numbers', unit:'u5', title:'أعداد 10 – 12', icon:'🔟', chip:'#e6e0ff',
    questions:[
      {type:'count', emoji:'⭐', count:10, options:[9,10,11]},
      {type:'count', emoji:'🍊', count:11, options:[10,11,12]},
      {type:'count', emoji:'🌼', count:12, options:[11,12,13]},
      {type:'mcq', prompt:'أيّ عدد يأتي بعد 11؟', options:[{text:'10',correct:false},{text:'12',correct:true},{text:'13',correct:false}]},
      {type:'mcq', prompt:'أيّ عدد يأتي قبل 10؟', options:[{text:'9',correct:true},{text:'11',correct:false},{text:'8',correct:false}]},
    ]},
  {id:'u5-plants', unit:'u5', title:'عالم النبات', icon:'🌻', chip:'#d8f5df',
    questions:[
      {type:'mcq', prompt:'ماذا يحتاج النبات لينمو؟', options:[{text:'الماء وضوء الشمس',correct:true},{text:'الحجارة فقط',correct:false}]},
      {type:'mcq', prompt:'أيّ جزء من النبات يصنع الغذاء؟', options:[{text:'الأوراق',correct:true},{text:'الجذور',correct:false}]},
      {type:'mcq', prompt:'ماذا يبدأ نمو النبات أولًا؟', options:[{emoji:'🌱',text:'البذرة',correct:true},{emoji:'🌳',text:'النبات الكبير',correct:false}]},
      {type:'tf', prompt:'تحتاج النباتات إلى الماء لتنمو.', correct:true},
      {type:'mcq', prompt:'الجزء الذي يمتصّ الماء من التربة هو:', options:[{text:'الجذور',correct:true},{text:'الأوراق',correct:false}]},
    ]},

  /* ---------- الوحدة السادسة: وطني الأردن ---------- */
  {id:'u6-letters', unit:'u6', title:'حروف: ق، خ، غ', icon:'🔤', chip:'#ffe6c2',
    questions:[
      {type:'mcq', prompt:'أيّ صورة تبدأ بحرف (ق)؟', options:[{emoji:'🚤',text:'قارب',correct:true},{emoji:'⚽',text:'كرة',correct:false}]},
      {type:'tf', prompt:'كلمة "قمر" تبدأ بحرف (ق).', correct:true},
      {type:'mcq', prompt:'أيّ صورة تبدأ بحرف (خ)؟', options:[{emoji:'🍞',text:'خبز',correct:true},{emoji:'🍎',text:'تفاحة',correct:false}]},
      {type:'tf', prompt:'كلمة "خيمة" تبدأ بحرف (خ).', correct:true},
      {type:'mcq', prompt:'أيّ صورة تبدأ بحرف (غ)؟', options:[{emoji:'🐦‍⬛',text:'غراب',correct:true},{emoji:'🐔',text:'دجاجة',correct:false}]},
      {type:'tf', prompt:'كلمة "غيمة" تبدأ بحرف (غ).', correct:true},
    ]},
  {id:'u6-english', unit:'u6', title:'English Letters: L, U', icon:'🔤', chip:'#e1fff5',
    questions:[
      {type:'mcq', prompt:'Which word starts with letter L?', options:[{emoji:'🍋',text:'lemon',correct:true},{emoji:'🐶',text:'dog',correct:false}]},
      {type:'tf', prompt:'The word "lion" starts with letter L.', correct:true},
      {type:'mcq', prompt:'Which word starts with letter L?', options:[{emoji:'💡',text:'lamp',correct:true},{emoji:'⚽',text:'ball',correct:false}]},
      {type:'mcq', prompt:'Which word means the position below something?', options:[{text:'under',correct:true},{text:'up',correct:false}]},
      {type:'tf', prompt:'The word "umbrella" starts with letter U.', correct:true},
      {type:'mcq', prompt:'Which word means the position above something?', options:[{text:'up',correct:true},{text:'under',correct:false}]},
    ]},
  {id:'u6-numbers', unit:'u6', title:'أعداد 13 – 15', icon:'🔢', chip:'#e6e0ff',
    questions:[
      {type:'count', emoji:'🚩', count:13, options:[12,13,14]},
      {type:'count', emoji:'🐑', count:14, options:[13,14,15]},
      {type:'count', emoji:'🏺', count:15, options:[14,15,16]},
      {type:'mcq', prompt:'أيّ عدد أكبر؟', options:[{text:'15',correct:true},{text:'13',correct:false}]},
      {type:'mcq', prompt:'العدد بين 13 و 15 هو:', options:[{text:'14',correct:true},{text:'16',correct:false},{text:'12',correct:false}]},
    ]},
  {id:'u6-jordan', unit:'u6', title:'معالم وطني', icon:'🇯🇴', chip:'#fff2c9',
    questions:[
      {type:'mcq', prompt:'ألوان علم وطني الأردن هي:', options:[{text:'الأسود والأبيض والأخضر والأحمر',correct:true},{text:'الأزرق والأصفر',correct:false}]},
      {type:'tf', prompt:'مدينة البتراء منحوتة في الصخر، وتقع في الأردن.', correct:true},
      {type:'mcq', prompt:'الكرة ⚽ شكلها:', options:[{text:'كروي',correct:true},{text:'أسطواني',correct:false}]},
      {type:'mcq', prompt:'علبة العصير 🥤 شكلها:', options:[{text:'أسطواني',correct:true},{text:'كروي',correct:false}]},
      {type:'mcq', prompt:'عاصمة وطني الأردن هي:', options:[{text:'عمّان',correct:true},{text:'بيروت',correct:false}]},
    ]},

  /* ---------- الوحدة السابعة: أصدقاء الأرض ---------- */
  {id:'u7-letters', unit:'u7', title:'حروف: ذ، ط، ك، ض', icon:'🔤', chip:'#ffe1e1',
    questions:[
      {type:'mcq', prompt:'أيّ كلمة تبدأ بحرف (ذ)؟', options:[{emoji:'🌽',text:'ذرة',correct:true},{emoji:'🐱',text:'قطة',correct:false}]},
      {type:'tf', prompt:'كلمة "ذبابة" تبدأ بحرف (ذ).', correct:true},
      {type:'mcq', prompt:'أيّ صورة تبدأ بحرف (ط)؟', options:[{emoji:'🦚',text:'طاووس',correct:true},{emoji:'🐟',text:'سمكة',correct:false}]},
      {type:'tf', prompt:'كلمة "محيط" تحتوي على حرف (ط).', correct:true},
      {type:'mcq', prompt:'أيّ صورة تبدأ بحرف (ك)؟', options:[{emoji:'⚽',text:'كرة',correct:true},{emoji:'🦆',text:'بطة',correct:false}]},
      {type:'tf', prompt:'كلمة "ديك" تنتهي بحرف (ك).', correct:true},
      {type:'mcq', prompt:'أيّ صورة تبدأ بحرف (ض)؟', options:[{emoji:'🐸',text:'ضفدع',correct:true},{emoji:'📖',text:'كتاب',correct:false}]},
      {type:'tf', prompt:'كلمة "أرض" تحتوي على حرف (ض).', correct:true},
    ]},
  {id:'u7-english', unit:'u7', title:'English Letters: Y, W, X, Z', icon:'🔤', chip:'#fff0e1',
    questions:[
      {type:'mcq', prompt:'Which word starts with letter Y?', options:[{emoji:'🥣',text:'yogurt',correct:true},{emoji:'🥛',text:'milk',correct:false}]},
      {type:'tf', prompt:'The word "yo-yo" starts with letter Y.', correct:true},
      {type:'mcq', prompt:'Which word starts with letter Y?', options:[{emoji:'🏡',text:'yard',correct:true},{emoji:'🏠',text:'house',correct:false}]},
      {type:'mcq', prompt:'Which word starts with letter W?', options:[{emoji:'🪟',text:'window',correct:true},{emoji:'🚪',text:'door',correct:false}]},
      {type:'tf', prompt:'The word "water" starts with letter W.', correct:true},
      {type:'mcq', prompt:'Which word starts with letter W?', options:[{emoji:'⌚',text:'watch',correct:true},{emoji:'📖',text:'book',correct:false}]},
      {type:'mcq', prompt:'Which word has letter X in it?', options:[{emoji:'📦',text:'box',correct:true},{emoji:'🐱',text:'cat',correct:false}]},
      {type:'tf', prompt:'The word "fox" contains letter X.', correct:true},
      {type:'mcq', prompt:'Which word has letter X in it?', options:[{emoji:'🕯️',text:'wax',correct:true},{emoji:'🖊️',text:'pen',correct:false}]},
      {type:'mcq', prompt:'Which word starts with letter Z?', options:[{emoji:'0️⃣',text:'zero',correct:true},{emoji:'1️⃣',text:'one',correct:false}]},
      {type:'tf', prompt:'The word "zoo" starts with letter Z.', correct:true},
      {type:'mcq', prompt:'Which word starts with letter Z?', options:[{emoji:'🦓',text:'zebra',correct:true},{emoji:'🐴',text:'horse',correct:false}]},
    ]},
  {id:'u7-numbers', unit:'u7', title:'أعداد 17 – 20', icon:'🔢', chip:'#e6e0ff',
    questions:[
      {type:'count', emoji:'⭐', count:17, options:[16,17,18]},
      {type:'count', emoji:'🚌', count:18, options:[17,18,19]},
      {type:'count', emoji:'🌙', count:19, options:[18,19,20]},
      {type:'count', emoji:'🌳', count:20, options:[18,19,20]},
      {type:'mcq', prompt:'أيّ عدد يأتي بعد 19؟', options:[{text:'18',correct:false},{text:'20',correct:true},{text:'21',correct:false}]},
    ]},
  {id:'u7-earth', unit:'u7', title:'أرضي الجميلة', icon:'🏔️', chip:'#cdeeda',
    questions:[
      {type:'mcq', prompt:'أيّ صورة تمثّل اليابسة؟', options:[{emoji:'⛰️',text:'جبل',correct:true},{emoji:'🌊',text:'محيط',correct:false}]},
      {type:'mcq', prompt:'أيّ صورة تمثّل الماء؟', options:[{emoji:'🌊',text:'بحر',correct:true},{emoji:'🏜️',text:'صحراء',correct:false}]},
      {type:'mcq', prompt:'في فصل الشتاء يكون الجوّ غالبًا:', options:[{text:'باردًا وممطرًا',correct:true},{text:'حارًّا جدًا',correct:false}]},
      {type:'mcq', prompt:'الرمز 🌧️ يدلّ على:', options:[{text:'المطر',correct:true},{text:'الثلج',correct:false}]},
      {type:'mcq', prompt:'من استخدامات الماء المهمّة:', options:[{emoji:'💧',text:'الشرب',correct:true},{emoji:'🔥',text:'إشعال النار',correct:false}]},
      {type:'tf', prompt:'يجب أن نحافظ على الماء ولا نبذّره.', correct:true},
    ]},
  {id:'u7-recycle', unit:'u7', title:'حافظ على الأرض', icon:'♻️', chip:'#d8f5df',
    questions:[
      {type:'mcq', prompt:'نضع الزجاجة الزجاجية المكسورة في الحاوية:', options:[{text:'الخضراء',correct:true},{text:'الحمراء',correct:false}]},
      {type:'mcq', prompt:'نضع علبة الصودا المعدنية في الحاوية:', options:[{text:'الحمراء',correct:true},{text:'الصفراء',correct:false}]},
      {type:'mcq', prompt:'دخان المصانع والسيارات يسبّب تلوّث:', options:[{text:'الهواء',correct:true},{text:'الماء',correct:false}]},
      {type:'mcq', prompt:'صوت أبواق السيارات العالي يسبّب تلوّثًا:', options:[{text:'سمعيًا',correct:true},{text:'بصريًا',correct:false}]},
      {type:'tf', prompt:'من الصحيح أن نرمي القمامة في الشارع.', correct:false},
    ]},

  /* ---------- الوحدة الثامنة: شكرًا روضتي ---------- */
  {id:'u8-letters', unit:'u8', title:'حروف: ظ، هـ', icon:'🔤', chip:'#ffe6ef',
    questions:[
      {type:'mcq', prompt:'أيّ كلمة تبدأ بحرف (ظ)؟', options:[{emoji:'🦌',text:'ظبي',correct:true},{emoji:'🐘',text:'فيل',correct:false}]},
      {type:'tf', prompt:'كلمة "ظرف" تبدأ بحرف (ظ).', correct:true},
      {type:'mcq', prompt:'أيّ كلمة تبدأ بحرف (هـ)؟', options:[{emoji:'🎁',text:'هدية',correct:true},{emoji:'📖',text:'كتاب',correct:false}]},
      {type:'tf', prompt:'كلمة "هلال" تبدأ بحرف (هـ).', correct:true},
    ]},
  {id:'u8-skills', unit:'u8', title:'مهارات وقيم', icon:'💖', chip:'#ffe6ef',
    questions:[
      {type:'mcq', prompt:'أيّ الإناءين يتّسع لكمية أكبر من الماء؟', options:[{text:'الإناء الكبير',correct:true},{text:'الإناء الصغير',correct:false}]},
      {type:'mcq', prompt:'السلحفاة 🐢 تتحرّك:', options:[{text:'ببطء',correct:true},{text:'بسرعة',correct:false}]},
      {type:'mcq', prompt:'الأرنب 🐇 يتحرّك:', options:[{text:'بسرعة',correct:true},{text:'ببطء',correct:false}]},
      {type:'tf', prompt:'من الأدب أن أشكر معلّمتي على جهدها.', correct:true},
      {type:'mcq', prompt:'عندما أرى شخصًا يحتاج مساعدة، أفعل:', options:[{text:'أساعده',correct:true},{text:'أتجاهله',correct:false}]},
    ]},

  /* ---------- عالم الرياضيات ---------- */
  {id:'math-addsub', unit:'math', title:'الجمع والطرح', icon:'➕', chip:'#e6e0ff',
    questions:[
      {type:'mcq', prompt:'2 + 3 = ؟', sub:'🍎🍎  +  🍎🍎🍎', options:[{text:'4',correct:false},{text:'5',correct:true},{text:'6',correct:false}]},
      {type:'mcq', prompt:'4 + 1 = ؟', sub:'🍊🍊🍊🍊  +  🍊', options:[{text:'4',correct:false},{text:'5',correct:true},{text:'6',correct:false}]},
      {type:'mcq', prompt:'5 - 2 = ؟', sub:'⭐⭐⭐⭐⭐  −  ⭐⭐', options:[{text:'2',correct:false},{text:'3',correct:true},{text:'4',correct:false}]},
      {type:'mcq', prompt:'3 + 3 = ؟', sub:'🎈🎈🎈  +  🎈🎈🎈', options:[{text:'5',correct:false},{text:'6',correct:true},{text:'7',correct:false}]},
      {type:'mcq', prompt:'4 - 1 = ؟', sub:'🍇🍇🍇🍇  −  🍇', options:[{text:'2',correct:false},{text:'3',correct:true},{text:'4',correct:false}]},
      {type:'mcq', prompt:'1 + 1 = ؟', sub:'🌼  +  🌼', options:[{text:'1',correct:false},{text:'2',correct:true},{text:'3',correct:false}]},
    ]},
  {id:'math-shapes', unit:'math', title:'الأشكال الهندسية', icon:'🔺', chip:'#ffe6c2',
    questions:[
      {type:'mcq', prompt:'الكرة ⚽ شكلها:', options:[{text:'دائرة',correct:true},{text:'مربع',correct:false}]},
      {type:'mcq', prompt:'صندوق النرد 🎲 شكله:', options:[{text:'مكعب',correct:true},{text:'دائرة',correct:false}]},
      {type:'mcq', prompt:'هذا الشكل 🔺 اسمه:', options:[{text:'مثلث',correct:true},{text:'مربع',correct:false}]},
      {type:'mcq', prompt:'هذا الشكل 🟥 اسمه:', options:[{text:'مربع',correct:true},{text:'دائرة',correct:false}]},
      {type:'mcq', prompt:'هذا الشكل 🔵 اسمه:', options:[{text:'دائرة',correct:true},{text:'مثلث',correct:false}]},
    ]},
  {id:'math-patterns', unit:'math', title:'الأنماط', icon:'🔁', chip:'#d8f5df',
    questions:[
      {type:'mcq', prompt:'ما الشكل التالي في النمط؟', sub:'🔴🔵🔴🔵🔴 ؟', options:[{text:'🔵',correct:true},{text:'🔴',correct:false}]},
      {type:'mcq', prompt:'ما الرمز التالي في النمط؟', sub:'⭐🌙⭐🌙⭐ ؟', options:[{text:'🌙',correct:true},{text:'⭐',correct:false}]},
      {type:'mcq', prompt:'ما اللون التالي في النمط؟', sub:'🟢🟢🟡🟢🟢🟡 ؟', options:[{text:'🟡',correct:true},{text:'🟢',correct:false}]},
      {type:'mcq', prompt:'ما العدد التالي في النمط؟', sub:'1، 2، 1، 2، 1، ؟', options:[{text:'2',correct:true},{text:'1',correct:false}]},
    ]},
  {id:'math-compare', unit:'math', title:'أكبر أو أصغر', icon:'⚖️', chip:'#ffe1e1',
    questions:[
      {type:'mcq', prompt:'أيّ عدد أكبر؟', options:[{text:'8',correct:true},{text:'5',correct:false}]},
      {type:'mcq', prompt:'أيّ عدد أصغر؟', options:[{text:'12',correct:false},{text:'7',correct:true}]},
      {type:'mcq', prompt:'أيّ مجموعة فيها عناصر أكثر؟', options:[{text:'أربع تفاحات 🍎🍎🍎🍎',correct:true},{text:'تفاحتان 🍎🍎',correct:false}]},
      {type:'tf', prompt:'العدد 15 أكبر من العدد 10.', correct:true},
      {type:'tf', prompt:'العدد 9 أصغر من العدد 6.', correct:false},
    ]},
  {id:'math-order', unit:'math', title:'ترتيب الأعداد', icon:'🔢', chip:'#cdeeda',
    questions:[
      {type:'mcq', prompt:'أيّ عدد يأتي بعد 12؟', options:[{text:'11',correct:false},{text:'13',correct:true},{text:'14',correct:false}]},
      {type:'mcq', prompt:'أيّ عدد يأتي قبل 10؟', options:[{text:'9',correct:true},{text:'11',correct:false},{text:'8',correct:false}]},
      {type:'mcq', prompt:'العدد بين 14 و 16 هو:', options:[{text:'15',correct:true},{text:'17',correct:false},{text:'13',correct:false}]},
      {type:'mcq', prompt:'أيّ ترتيب من الأصغر إلى الأكبر صحيح؟', options:[{text:'3 ، 7 ، 9',correct:true},{text:'9 ، 3 ، 7',correct:false}]},
      {type:'mcq', prompt:'أيّ عدد أكبر: 20 أم 18؟', options:[{text:'20',correct:true},{text:'18',correct:false}]},
    ]},
  {id:'math-tens', unit:'math', title:'القفز بالعشرات', icon:'🦘', chip:'#fff2c9',
    questions:[
      {type:'mcq', prompt:'أُكمل القفز بالعشرات:', sub:'10 ، 20 ، 30 ، ؟', options:[{text:'35',correct:false},{text:'40',correct:true},{text:'50',correct:false}]},
      {type:'mcq', prompt:'أُكمل القفز بالعشرات:', sub:'10 ، 20 ، ؟ ، 40', options:[{text:'25',correct:false},{text:'30',correct:true},{text:'35',correct:false}]},
      {type:'mcq', prompt:'ما العدد الناقص في بداية القفز؟', sub:'؟ ، 20 ، 30 ، 40', options:[{text:'5',correct:false},{text:'10',correct:true},{text:'15',correct:false}]},
      {type:'mcq', prompt:'أُكمل القفز بالعشرات:', sub:'10 ، 20 ، 30 ، 40 ، ؟', options:[{text:'45',correct:false},{text:'50',correct:true},{text:'60',correct:false}]},
      {type:'tf', prompt:'عند القفز بالعشرات، العدد الذي يأتي بعد 30 هو 40.', correct:true},
      {type:'mcq', prompt:'أيّ عدد يظهر عند القفز بالعشرات ابتداءً من 10؟', options:[{text:'25',correct:false},{text:'30',correct:true}]},
    ]},
];
